#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O -J $PROXY $1; cd -
}

VERSION=$(gh_releases ladybirdweb/faveo-helpdesk | grep -v '^v\.' | sort -V | tail -1)
URL="https://github.com/ladybirdweb/faveo-helpdesk/archive/refs/tags/${VERSION}.tar.gz"
SRC=/usr/local/src

dl $URL $SRC


#install inoncube loader
systemctl restart apache2
wget http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
tar -xvf ioncube_loaders_lin_x86-64.tar.gz
cp ioncube/ioncube_loader_lin_8.2.so /usr/lib/php/20220829
