#!/bin/bash -ex

VERSION=v2.0.3
ARCHIVE=faveo-helpdesk-${VERSION#v}.tar.gz
SHA256=8b42f15c164a2e7cdf87ab53ed00c3c806ac7efa96e201405886fe559af93252
URL="https://github.com/faveosuite/faveo-helpdesk/archive/refs/tags/${VERSION}.tar.gz"
SRC=/usr/local/src

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f -o "$SRC/$ARCHIVE" $PROXY "$URL"
echo "$SHA256  $SRC/$ARCHIVE" | sha256sum --check
