#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O -J $PROXY $1; cd -
}

VERSION=$(gh_releases ladybirdweb/faveo-helpdesk | grep -v '^v\.' | sort -V | tail -1)
URL="https://github.com/ladybirdweb/faveo-helpdesk/archive/${VERSION}.tar.gz"
SRC=/usr/local/src

dl $URL $SRC
