#!/bin/bash -ex

DB_NAME=faveo
DB_USER=faveo
DB_PASS=$(mcookie)

ADMIN_USER="admin"
ADMIN_DOMAIN="example.com"
ADMIN_MAIL="${ADMIN_USER}@${ADMIN_DOMAIN}"
ADMIN_PASS=turnkey1
ADMIN_FNAME="TurnKey"
ADMIN_LNAME="Linux"

SRC=/usr/local/src
WEBROOT=/var/www/faveo-helpdesk
CONF=$WEBROOT/.env

LOC_SHARE=/usr/local/share
LOC_BIN=/usr/local/bin

# install Faveo
tar xf $SRC/faveo-helpdesk-*.tar.gz -C /var/www
mv $WEBROOT* $WEBROOT
chown -R www-data:www-data $WEBROOT
rm -f $SRC/faveo-helpdesk-*.tar.gz

systemctl start  mysql

mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# Ensure that turnkey-artisan knows where webroot is
sed -i "\|^export WEBROOT| s|=.*|="$WEBROOT"|" /usr/local/bin/turnkey-artisan

cd $WEBROOT

sed -i "s|DB_PASS|$DB_PASS|g" $SRC/install.exp
$SRC/install.exp
$SRC/populate-db.exp

mysql --batch --execute "update faveo.users set user_name='$ADMIN_USER', first_name='$ADMIN_FNAME', last_name='$ADMIN_LNAME' where id='1';"
/usr/lib/inithooks/bin/faveo-helpdesk.py --email="$ADMIN_MAIL" --pass="$ADMIN_PASS"

turnkey-artisan config:cache
turnkey-artisan key:generate --force
turnkey-artisan config:clear

chown -R www-data:www-data $WEBROOT

# not sure why this app appears to be the only one that complains about this; but...
chmod 1733 /var/lib/php/sessions

# finalise redis config
cd $WEBROOT/config
# Also update DB settings
mysql --batch --execute "update faveo.queue_services set status=0 where short_name='sync';"
mysql --batch --execute "update faveo.queue_services set status=1 where short_name='redis';"
COLUMNS="\`service_id\`, \`key\`, \`value\`, \`created_at\`, \`updated_at\`"
mysql --batch --execute "insert into faveo.faveo_queues (${COLUMNS}) values (6, 'driver', 'redis', NOW(), NOW()), (6, 'queue', 'default', NOW(), NOW());"

a2dissite 000-default
a2ensite faveo-helpdesk
a2enmod rewrite

systemctl stop  mysql

# cleanup
apt purge --autoremove expect -y
