#!/bin/bash -e
# regenerate faveo-helpdesk secrets and mysql user password

. /etc/default/inithooks

WEBROOT=/var/www/faveo-helpdesk
CONF=$WEBROOT/.env

DB_USER=faveo
DB_PASS=$(mcookie)

sed -i "\|DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

sed -i "\|API_SECRET=|s|=.*|=$(mcookie)$(mcookie)|" $CONF

turnkey-artisan config:cache
turnkey-artisan key:generate --force
turnkey-artisan config:clear
