#!/bin/bash -e
# set faveo-helpdesk admin password & email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/faveo-helpdesk.py --pass="$APP_PASS" --email="$APP_EMAIL"
